name: Docker run
on: 
  push: 
    branches: ["main"]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      uses: appleboy/ssh-action@v1.0.0
      env: 
        RUN_ID: "$GITHUB_RUN_ID"
      with: 
        host: 121.41.72.174
        username: root
        password: Abc123456
        envs: RUN_ID
        script: |
          echo "run_id: $RUN_ID"
