name: Docker run
on: 
  push: 
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: maven build
      run: echo "maven build.."
    - name: docker build
      run: echo "docker build..."
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy
      run: echo "deploy..."
  
  
  
